import './globals.scss';

import AuthContextProvider from '@/components/context/AuthContextProvider';
import Navbar from '@/components/shared/Navbar';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
      <body className='pb-12 bg-background-base text-text-base antialiased'>
        <AuthContextProvider>
          <Navbar />
          <main>{children}</main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
